granulate_utils/linux/oom.py
granulate_utils/linux/signals.py

This includes extracting OOM events & exception signals (SIGSEGV, traps, ...) from kernel messages, which we plan to use in gProfiler among other components.

Initial version with first utils

---

granulate_utils/java.py

* Regexes for native frames, siginfo, container info, and vm info.
* Error file location helper.

Add Java Hotspot error log helpers

---

granulate_utils/linux/oom.py
granulate_utils/linux/proc_events.py
granulate_utils/linux/signals.py
mypy.ini

Also including a fix to the listener loop which would previously crash when handled too many events, and ignoring missing imports for the psutil library which failed `lint.sh` for me

Added support for registering on process exec events

---

setup.py

mypy will find the py.typed file and actually check the types :)

Make package PEP-561 compliant

---

granulate_utils/linux/process.py

Added process utility functions to handle edge cases where processes are zombies

Add process utils to handle zombie processes

---

granulate_utils/linux/ns.py

Added a function that returns a process's host pid given its nspid and container id

Added `get_host_pid` function

---

dev-requirements.txt

See https://github.com/Granulate/gprofiler/pull/324

Upgrade Black

---

dev-requirements.txt

Upgrade mypy to 0.942, as 0.910 is almost a year old.

Upgrade mypy to 0.942

---

requirements.txt

Fix conflicts on other projects after mypy upgrade to 0.942

Upgrade typing-extensions and requests

---

requirements.txt

Update docker version to ~5.0.0 for pineapple compatibility

Update docker version to ~5.0.0 for pineapple compatability

---

granulate_utils/linux/process.py

Add `read_proc_file` to read arbitrary `/proc/PID/...` file, while translating all the needed exceptions appropriately.
I have verified that the changed methods still work fine.

linux: process: Add read_proc_file helper

---

dev-requirements.txt
requirements.txt

Follows https://github.com/Granulate/gprofiler/pull/519
Fixes what was added in #82 and I wanted fixed in https://github.com/Granulate/granulate-utils/pull/84

Upgrade flake8

---

granulate_utils/metadata/cloud.py

Tested in Google Cloud Shell:
```python3
import requests
resp = requests.get('http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true', headers={'Metadata-Flavor': 'Google'})
j = resp.json()
j['zone'].rpartition('/')[2], j['machineType'].rpartition('/')[2]
```
```console
Out[3]: ('europe-west4-b', 'e2-standard-2')
```

metadata: GCP: Strip project prefix from zone field

---

granulate_utils/linux/cgroups/base_cgroup.py
granulate_utils/linux/cgroups/cpuacct_cgroup.py
granulate_utils/linux/cgroups/memory_cgroup.py

Added:
- Ability to get memory usage
- `cpuacct` class that allows getting cpu usage
- `pids_in_cgroup` propery.

Added more parsing to cgroup classes

---

granulate_utils/linux/cgroups/cpu_cgroup.py
granulate_utils/linux/cgroups/cpuacct_cgroup.py

Added get_stat to CpuCgroup, and fixed typing on CpuAcctCgroup

---

granulate_utils/linux/cgroups/__init__.py
granulate_utils/linux/cgroups/cgroup.py

Implemented and exported `get_cgroup_mount(controller)`

Add utility function that returns a cgroup controller folder

---

granulate_utils/metadata/cloud.py

I still need to see precisely why, but it seems that on some AWS instances (and possibly some Docker settings), a running container such as gProfiler is inaccessible from its net NS to the cloud metadata endpoint. I have some AWS instance now where gProfiler started not in host net NS fails to get cloud info, starting it with `--net=host` succeeds in getting cloud info, and I tested this branch and it succeeds as well.
I took some care to avoid wrapping unnecessary parts in `run_in_ns` (e.g the `logger` call which for all we know can trigger networking operations). The smallest section possible would be in `send_request`, but I think what I did is good enough

Run cloud metadata queries in host net NS

---

glogger/extra_adapter.py

I thought mypy would've caught it

glogger: Fix Python 3.8 compatibility

---

granulate_utils/linux/process.py

Fixes this case:
```
File "granulate_utils.linux.process", line 77, in read_process_execfn
File "granulate_utils.linux.process", line 93, in _read_process_auxv
ValueError: auxv id 31 was not found!
```
which happens when the function is called on kernel threads / zombie processes.

linux: process: Handle errors in _read_process_auxv()

---

granulate_utils/linux/process.py

Kernel frees task mm first before updating the process status, so it's state might be still "alive". But it will become zombie/dead very soon anyway.

linux: handle exit()-ing process when reading auxv

---

granulate_utils/java.py
tests/granulate_utils/test_jvm_flags.py

Add jvm flags parsing to use in gProfiler agent

Add jvm flags parsing

---

granulate_utils/python.py

As mentioned in https://github.com/Granulate/gprofiler/pull/701#discussion_r1115640037

Change Python process regex to ERE friendly

---

granulate_utils/metrics/__init__.py
granulate_utils/metrics/yarn.py

Add a `ResourceManager` API class that can be used independently of the `YarnCollector`.

metrics: yarn: ResourceManager API

---

glogger/sender.py

See https://github.com/Granulate/gprofiler/pull/765

glogger: sender: Allow disabling certificate verification

---

granulate_utils/metadata/databricks_client.py

for review convenience
exact copy from gprofiler f120423
minor adjustment of logger 746a5e6

Copy gProfilers' Databricks client with minor adjustments

---

granulate_utils/metadata/databricks_client.py

note there are some comments I left to ease the review process

DBX wrapper refactor

---

granulate_utils/metadata/bigdata/__init__.py
granulate_utils/metadata/bigdata/databricks.py
granulate_utils/metadata/bigdata/dataproc.py
granulate_utils/metadata/bigdata/emr.py

exact copy from gProfiler 7eb8a0b
minor `granulate-utils` adjustments 978232a

Metadata: bigdata: exact copy from gProfilers' metadata collection on big data instances

---

tests/granulate_utils/test_bigdata.py

was copied from https://github.com/Granulate/gprofiler/pull/811

Metadata: bigdata: unit tests copy from gProfiler

---

granulate_utils/linux/elf.py

This PR is addressing comments: https://github.com/Granulate/gprofiler/pull/815#discussion_r1242725764
Connected with: https://github.com/Granulate/gprofiler/issues/804

Use raise_nosuchprocess decorator in elf.py

---

granulate_utils/metadata/cloud.py

Tested on Fargate.
```yaml
container_arn: arn:aws:ecs:us-east-1:XXXXXX:container/...
execution_env: AWS_ECS_FARGATE
provider: aws
region: us-east-1
```

Fetch AWS ECS container metadata

---

granulate_utils/config_feeder/client/base.py
tests/granulate_utils/config_feeder/test_emr_yarn_collector.py

Collect information within the error message about the path that failed.

add information about max retries error

---

granulate_utils/linux/elf.py

Should've just used "EM_AARCH64" lol.

Fix "Aarch64" -> "AArch64"

---

granulate_utils/metrics/yarn/resource_manager.py
tests/granulate_utils/metrics/test_resource_manager.py

RM version check fails when vendor suffix is present
try to extract semver before comparison

fix: RM version check fail

---

granulate_utils/exceptions.py
granulate_utils/metadata/databricks_client.py
granulate_utils/metrics/__init__.py
granulate_utils/metrics/sampler.py
granulate_utils/metrics/spark.py

This pull request improves databricks metadata client, adds more logging, and adds the ability to control its defaults.
Also, it adds support to control parameters when accessing SparkUI for metrics.

databricks client: use exceptions and add logging, SparkUI requests control

---

granulate_utils/metrics/yarn/resource_manager.py

Generic resource manager request required for MapReduce jobs

Add generic rm request method

---

granulate_utils/linux/elf.py
requirements.txt

Remove type: ignore from elftools and fix wrap_as_nosuchprocess

---

granulate_utils/metadata/bigdata/__init__.py
granulate_utils/metadata/bigdata/bigdatainfo.py
granulate_utils/metadata/bigdata/interfaces.py
tests/granulate_utils/test_bigdata.py

fix bigdata metadata to explicitly export functions required by config feeder client node info
It does not change anything except moving stuff around and explicit exports to fix

fix bigdata metadata to exports

---

granulate_utils/metadata/databricks_client.py

part of LEGO-378
see https://github.com/Granulate/granulate/pull/23844

reduce dbx metadata exception errors

---

glogger/sender.py
tests/glogger/test_handler.py

Resolve: https://app.clickup.com/t/86byqmh6t

added clear error messages for different failures sending remote logs

---

dev-requirements.txt
granulate_utils/linux/mountinfo.py
requirements.txt
tests/granulate_utils/test_jvm_version.py

When his repo was recently moved from granulate to intel in GitHub. In the processes, IPASS scans were enabled and several CVEs in dependency versions were identified. This PR upgrades the packages with the versions that mitigate these CVEs.

Updated dependency versions with outstanding CSVs
