- granulate_utils/linux/proc_events.py
So if an exception is raised during the bind()/_register_for_connector_events(),
it is visible in the calling thread.
> Start proc_events in the calling thread

- granulate_utils/linux/__init__.py
- granulate_utils/linux/oom.py
- granulate_utils/linux/signals.py
`\w+` works for e.g `java` but not for names containing `-`, which are common (`systemd-...`).
> Improve OOM regex

- granulate_utils/linux/ns.py
A little API change - make get_mnt_ns_ancestor return a `Process` object instead of a pid.
Makes the function a little more generic and also will be used in https://github.com/Granulate/gprofiler/pull/240 to cache per namespace instead of per PID.
> Linux: ns: Return Process in get_mnt_ns_ancestor

- enable_hook.sh
- granulate_utils/exceptions.py
- granulate_utils/linux/ns.py
Make `get_process_nspid()` work with old kernels
Tested on Ubuntu 14.04 `3.13.0-170-generic`
> linux: ns: get_process_nspid() support old kernels

- granulate_utils/linux/proc_events.py
Moved from gProfiler's `java.py`. This should be here as it is required from all users of `proc_events`, not solely `java.py`.
gProfiler PR: https://github.com/Granulate/gprofiler/pull/280
> proc_events: bind() in init net NS

- granulate_utils/linux/containers.py
- granulate_utils/linux/ns.py
Based on (and fixes some of) https://github.com/Granulate/granulate-utils/pull/24
Matching gProfiler PR: https://github.com/Granulate/gprofiler/pull/278
Improved the function a bit along the way.
> Move get container id to utils

- granulate_utils/exceptions.py
- granulate_utils/linux/cgroups.py
- granulate_utils/linux/containers.py
Add `get_cgroups` to parse process cgroups into list of (hierarchy id., controllers, path) tuples.
> linux: Add get_cgroups helper

- granulate_utils/linux/ns.py
`resolve_proc_root_links` would check if some path is a link and resolve it, but then it wouldn't recheck if the resolved path is still a link. We now perform the check in a loop while keeping a set of checked paths to detect a symlink loop.
Note that while `os.path.realpath` and `os.path._joinrealpath` perform similar functionality, they won't prepend the `proc_root` prefix correctly after each link resolving.
> linux/ns: Support recursive symlinks in resolve_proc_root_links

- granulate_utils/exceptions.py
- granulate_utils/linux/process.py
handling a case of a non-zombie process with no EXE path available in the function process_exe
in the current behavior is that an empty string is returned, the change I am suggesting here is to raise an exception in case of no EXE is available but the process is not zombie
> bugfix: raise error when exe path is empty

- granulate_utils/linux/ns.py
I had a hard time debugging some code that uses `is_same_ns` after I found I used `mount` instead of `mnt` as the nstype :(
> Statically enforce ns types literal to avoid typos in nstypes in various callsites

- granulate_utils/metadata/cloud.py
On GCP, we access the `machineType` metadata which contains more parts than we are interested in.
> Keep only the last part of the GCP machine type

- granulate_utils/linux/ns.py
I checked other uses of `/status` - only other one is in gprofiler `process_comm` where this won't affect us.
> Handle empty lines in /proc/pid/status

- granulate_utils/containers/docker.py
I got this race:
```
...
File "granulate_utils.containers.client", line 44, in list_containers
File "granulate_utils.containers.docker", line 24, in list_containers
File "docker.models.containers", line 953, in list
File "docker.models.containers", line 889, in get
File "docker.utils.decorators", line 19, in wrapped
File "docker.api.container", line 773, in inspect_container
File "docker.api.client", line 274, in _result
File "docker.api.client", line 270, in _raise_for_status
File "docker.errors", line 31, in create_api_error_from_http_exception
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/xxx/json: Not Found ("No such container: xxx")
```
Found a ticket in docker-py suggesting the use of `ignore_removed`, …
> containers: docker: Avoid race in DockerClient.list_containers()

- mypy.ini
When running `lint.sh` on Mac mypy cries with:
```console
error: "Process" has no attribute "memory_maps"
```
because `memory_maps` is defined on `Process` only when platform is not "darwin": https://github.com/python/typeshed/blob/master/stubs/psutil/psutil/__init__.pyi#L191
> mypy: set platform to linux

- requirements.txt
The requirements are too strict and prevent installation of newer patch versions.
> Relax requirements

- granulate_utils/exceptions.py
- granulate_utils/linux/cgroups/__init__.py
- granulate_utils/linux/cgroups/base_cgroup.py
- granulate_utils/linux/cgroups/cgroup.py
- granulate_utils/linux/containers.py
- granulate_utils/linux/ns.py
- mypy.ini
Added `find_v1_hierarchies` and `find_v2_hierarchy` to find where the hierarchies for v1/v2 controllers are mounted.
> cgroups: Find v1/v2 hierarchies

- granulate_utils/containers/cri.py
- granulate_utils/containers/docker.py
- granulate_utils/linux/cgroups/cgroup.py
- granulate_utils/linux/proc_events.py
last commit had circular import issue - this solves it.
tested by executing all imports of granulate-utils in a separate python3 shell.
> fix circular import of ns

- granulate_utils/golang.py
- granulate_utils/linux/process.py
- granulate_utils/node.py
Most of the code is copied from:
https://github.com/Granulate/gprofiler/blob/master/gprofiler/profilers/perf.py#L272
And will be used there as well.
> Added golang and node process utils

- granulate_utils/linux/cgroups/memory_cgroup.py
1. Ensure we reset `memsw.limit_in_bytes` (in case it exists) in order to allow changing `limit_in_bytes` in case it's smaller than `memsw.limit_in_bytes` (or we will experience `write error: Invalid argument`)
2. Fix `reset_memory_limit` which previously didn't reset  `memsw.limit_in_bytes` (in case it exists)
> cgroups: memory: fixed set_limit_in_bytes

- granulate_utils/linux/elf.py
Added get_elf_arch() that reads the binary architecture from the ELF section of the file
> Added get_elf_arch() that reads the binary architecture from the ELF section of the file

- glogger/sender.py
- glogger/stdout_logger.py
Adding formatting to stdout handler so we have level and time and not just the message.
Also removing the special handling of HTTPError in the sender - so we have the actual error in the log.
> glogger: Add formatting to stdout_handler

- granulate_utils/linux/elf.py
- lint.sh
To avoid the case of someone creating a venv but forgetting to install `dev-requirements.txt` inside and then running mypy/isort/black from outside of the venv - use `python3 -m foo` instead of `foo` for all linters
> lint: Avoid using binaries from outside the venv

- README.md
Following discussions around catching `pyelftools.ELFError` raised from `granulate-utils` in other projects - the decision was to expose only standard library (+psutil&requests) exceptions as part our APIs, all else should be re-raised or re-exported.
> README: Add a note on exposing exceptions

- granulate_utils/linux/cgroups/base_cgroup.py
- granulate_utils/linux/cgroups/cgroup.py
- granulate_utils/linux/containers.py
1. Updates `get_cgroups()` to use `read_proc_file` to catch errors better.
2. Removes ability to specify plain int pid to `get_process_container_id`, to force users to rely on `psutil.Process` at all times. (To reap the advantages of `psutil.Process` it must be used at all times, as early as possible.)
3. Makes `get_cgroups()` default to getting the cgroups of the current process if the parameter is not given. This is a shorthand for `get_cgroups(os.getpid())` which appears a couple times in the code.
> Use read_proc_file in get_cgroups()

- granulate_utils/linux/elf.py
It wraps function get_elf_id(), if that function throws FileNotFound exception then wrapper checks if not found file is /proc/{pid}/*, if it is, wrapper changes exception to NoSuchProcess.
Connected to: https://github.com/Granulate/gprofiler/issues/503
> Add wrapper for catching FileNotFound Exception

- granulate_utils/linux/elf.py
Adds `get_libc_type` function to `elf.py`, it distinguishes between dynamic glibc/musl and for static - between libc existing an not existing.
It is harder to distinguish between musl/glibc in static binaries and technically, not really needed for our use cases.
I am 50/50 about splitting it to `get_dynamic_libc_type` and `is_static_libc` that just do their respective parts, lmk what you think.
As an aside - we really need to move this to a class so we don't need to re-read the elf for each function. We can keep the global functions as a convenience wrapper. Specifically - `get_libc_type` reads the elf twice, lmk if you want me to do the refactor to a class right now to avoid this.
> elf: Add get_libc_type

- granulate_utils/golang.py
`process_exe` resolves links. It fails path access inside dockers.
> Golang removed process_exe usage

- granulate_utils/golang.py
- granulate_utils/linux/process.py
- granulate_utils/node.py
The purpose of this PR is to avoid checking if kernel threads are golang/node processes.
> Added is_kernel_process function and used it in golang and node runtimes

- granulate_utils/linux/ns.py
It's a bad practice to have it defaulting to False, and it's a bad practice to use it with False anyway
> ns: run_in_ns(): Remove passthrough_exception

- granulate_utils/linux/process.py
When processes have been run with full path as argv0 - for example `/usr/bin/java` the function returned False on real true cases
> granulate utils: fix process argv0 match check

- granulate_utils/linux/cgroups/cpu_cgroup.py
- tests/granulate_utils/test_cgroups.py
Take into account that a cgroup can be unlimited (`cfs_quota_us` is set to -1).
> granulate_utils: Handle unlimited cgroup quota

- granulate_utils/linux/mountinfo.py
When running in a thread which is in a different namespace, `/proc/self/...` will return the information from the process's namespaces instead of the thread's namespaces.
> linux: Use /proc/tid/mountinfo instead of /proc/self/mountinfo

- .github/workflows/granulate-utils.yml
- granulate_utils/futures.py
- granulate_utils/metadata/cloud.py
- tests/granulate_utils/test_futures.py
* Add the `call_in_parallel` utility for convenience
* Use `call_in_parallel` in `get_static_cloud_instance_metadata` so we don't waste time if we're in the wrong cloud provider
> granulate_utils: Improve cloud info fetching performance

- granulate_utils/metrics/sampler.py
currently, in gProfiler, `discover()` is invoked every 5 seconds 10 minutes.
in any case that gProfiler is installed on every instance in a cluster, the next logs will heavily appear for the first 10 minutes:
[Could not find any spark master process (resource manager or spark master)
](https://github.com/Granulate/granulate-utils/pull/145/files#diff-e8dd154b7df986eb768fe56114e039f44a244a6a5d75f464611aa95fcb21866fL239)[Trying to guess cluster mode and master address](https://github.com/Granulate/granulate-utils/pull/145/files#diff-e8dd154b7df986eb768fe56114e039f44a244a6a5d75f464611aa95fcb21866fL300)
also, removed the next log:
[Guessed cluster mode and master address](https://github.com/Granulate/granulate-utils/pull/145/files#diff-e8dd154b7df986eb768fe56114e039f44a244a6a5d75f464611aa95fcb2 …
> Spark: removed spammy debug logs in discover()

- glogger/sender.py
this PR adds authentication parameters to the Sender requests to allow G-Logger Backend to authenticate the request using aws token **or** g-profiler token. 
new params:
-  x_auth_type: The type of authentication to use. ('aws')
-  x_auth_access_key_id: The access key id to use for authentication.
-  x_auth_secret_access_key: The secret access key to use for authentication.
> add auth method params

- granulate_utils/linux/elf.py
Connected with: https://github.com/Granulate/gprofiler/issues/804.
As far as I understand if executable has debug information it is not-stripped, and if it hasn't then it is stripped. According to pyelftools this information is stored in has_debug_info property in DWARFInfo object which can be obtained by using get_dwarf_info() method on elf file.
> Add method to check if exe is stripped

- granulate_utils/metrics/yarn.py
Add a new ResourceManagerAPI endpoint for yarn queues (related pr: https://github.com/Granulate/granulate/pull/17311)
> Add scheduler to resourcemanager api

- granulate_utils/golang.py
- granulate_utils/linux/elf.py
Support identification of Golang binaries by looking for ELF section `.note.go.buildid`, supported since Go 1.5.
Reference: https://github.com/golang/go/issues/11048.
> Add identification of golang binaries

- granulate_utils/java.py
- tests/granulate_utils/test_jvm_version.py
1. better regex:
e.g. this regex was failed to match the [functions' own `java -version` output example](https://github.com/Granulate/granulate-utils/blob/dadafab/granulate_utils/java.py#L136)
2. on my PC it's `Java HotSpot(TM) 64-Bit Server VM`... so I added support
3. replaced `TODO` with an informative comment
4. tests, including the documented `java -version` example from `parse_jvm_version()`
one question I have is why do we need the regex? why can't we just `lines[2].startswith()` or even `if 'HotSpot' in lines[2]`?
> Java: fix `parse_jvm_version` `vm_name` regex pattern

- granulate_utils/metrics/yarn.py
HADOOP v2 and v3 behaves differently. In hadoop v2 nested JSON objects can contain nulls.
e.g. `curl http://localhost:8088/ws/v1/cluster/apps?finalStatus=KILLED`
v3 response: `{"apps":{}}`
v2 response: `{"apps":null}`
> fix: hadoop v2.6.0 compatibility

- granulate_utils/__init__.py
- setup.py
This PR automates versioning using `git-describe`.
Versions are in the form of `0.0.2.post<N>+git.<hash>`
The `.post<N>` part is [PEP 440 (versioning) compliant](https://peps.python.org/pep-0440/#post-releases) so `pip` knows how to order these. It is incremented with every commit.
No changes required in the various `requirements.txt`s
> git based version

- glogger/extra_adapter.py
- glogger/extra_exception.py
- tests/glogger/test_extra_adapter.py
This PR adds the ability for `ExtraAdapter` to collect `extra` attrs from Exception objects, for use when doing:
`adapater.exception("An exception has occured")`
For convenience, also added an `ExtraException` base-class
> Glogger extra exception

- granulate_utils/containers/container.py
- granulate_utils/containers/cri.py
- granulate_utils/containers/docker.py
To guard against pid reuse after container exits.
> containers: use Process objects instead of pids

- granulate_utils/linux/ns.py
In some environments such as Databricks and Fargate, some processes may be restricted and return EACCESS on `readlink('/proc/<pid>/ns/pid')`, we don't want these processes to fail `get_host_pid`.
> Suppress PermissionError in get_host_pid due to restricted processes

- granulate_utils/linux/cgroups_v2/cgroup.py
Currently, if cgroup relative path of process is "/" (meaning this is the root cgroup path), we will fail creating the cgroup object. This is because we treat "/" the same way we treat controller not found.
> bugfix: Support root cgroup path

- granulate_utils/linux/ns.py
- tests/granulate_utils/test_ns_utils.py
Fix resolve_proc_root_links handling of links that resolve to sub-path links.
Example:
```
{tmpdir}/link
link -> {tmpdir}/a/c
a -> {tmpdir}/b
Eventually we expect {tmpdir}/link to resolve to {tmpdir}/b/c
```
> granulate-utils: Fix resolve_proc_root_links

- granulate_utils/linux/process.py
Fix a bug that resulted in psutil's cache. The fix is clearing the cache before using the exe.
> Clear psutil's process exe cache

- dev-requirements.txt
backoff isn't required by this package, and this dev-requirement fails my CI for projects that have both `granulate-utils` and `backoff>2`
> Remove backoff-stubs

- granulate_utils/linux/cgroups_v2/cgroup.py
- tests/granulate_utils/test_cgroups.py
In a machine with Cgroups V1, by default Docker doesn't enter a cgroup namespace (`--cgroupns=host`).
Inside the container, as subtree of the host cgroup hierarchy is mounted:
```
712 709 0:34 /docker/<guid> /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,cpu,cpuacct
```
Meaning that accessing `/sys/fs/cgroup/<controller>/something` inside the container is the same as accessing `/sys/fs/cgroup/<controller>/docker/<guid>/something` from the host.
Reading from `/proc/pid/cgroup` yields a path in the **host** mount:
`3:cpu,cpuacct:/docker/<guid>`.
To  access this cgroup from within the container, we need to strtip the `/docker/<guid>` part.
> cgroup v1 take into account mount root

- granulate_utils/linux/cgroups_v2/cgroup.py
- tests/granulate_utils/test_cgroups.py
Fix bugs introduced by the [original PR](https://github.com/Granulate/granulate-utils/pull/237)
`with_new_path` has to take care of both the absolute path case `/sys/fs/cgroup/....` and the looks-like-absolute-from-/proc/pid/cgroup-case `/docker/<guid>`.
We can't split into two functions because `get_cgroup_core(path)` is called externally with all kinds of paths
> cgroup v1 take into account mount root - bugfixes

- granulate_utils/linux/cgroups_v2/__init__.py
- granulate_utils/linux/cgroups_v2/cgroup.py
- granulate_utils/linux/cgroups_v2/systemd_controller.py
Add code to manipulate the Systemd cgroups hierarchy:.=
On Cgroups V1, manipulate the `name=systemd` controller.
On Cgroups V2, manipulate the cgroup hierarchy regardless of supported controllers (empty controller).
This is needed because Systemd keeps track of process assignment to units by their cgroups: if the V2 hierarchy is mounted, it acts as the source of truth - regardless of which controllers are enabled or delegated. If the V2 hierarchy is not mounted, a `name=systemd` controller is created to the V1 hierarchy and become the source of truth.
> cgroups: systemd controller manipulation

- granulate_utils/linux/ns.py
- granulate_utils/linux/proc_events.py
- granulate_utils/metadata/cloud.py
This PR adds support for running gprofiler without root/sudo as discussed in issue 905 in the gprofiler repo: https://github.com/Granulate/gprofiler/issues/905. 
It creates run_in_ns_wrapper function which bypasses the code to enter name spaces when not root (as we assume we're always in the correct namespace for the processes being profiled). 
This commit is required for PR 936 in the gprofiler repo https://github.com/Granulate/gprofiler/pull/936.
I have tested this on x86 using scripts/build_x86_64_executable.sh script. Centos 9 Stream w/ kernel 6.6, though with some limitations mentioned in the gprofiler PR.
The code is linted.
One issue is when running on one system, I receive the below warning (though gprofiler completes and produces valid results)
> 	[2024-12-02 19:59:55,557] …
> Added run_in_ns_wrapper to only run in namespace when root is detected.
